

# Generated by Django 4.2.6 on 2023-10-30 15:25

from django.db import migrations

def combine_names(apps, schema_editor):    
    Post = apps.get_model("blog", "Post")
    User = apps.get_model("auth", "User")
    user = User.objects.all()[:1].get()
    for i in range(1,31):
        post = Post(title = f"Пост {i}", text = f"Текст поста {i}", 
                    author =  user)
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [migrations.RunPython(combine_names)]